name: Local
variables:
  - name: baseUrl
    value: http://localhost:3000/api
  - name: token
    value: ""
  - name: refreshToken
    value: ""
  - name: claimId
    value: ""
  - name: itemId
    value: ""
  - name: userId
    value: ""
  - name: departmentId
    value: 69b445763061b872ebfe7bcc
  - name: budgetId
    value: ""
  - name: attachmentId
    value: ""
